// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.3.0")]
[assembly: AssemblyFileVersionAttribute("1.3.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.3.0";
    }
}
